/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package unifacs.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import unifacs.controller.TelaUsuarioController;

/**
 *
 * @author YellowRed
 */
public class JITelaPagamento extends javax.swing.JInternalFrame {

    private JITelaPedidoRestaurante1 viewPedidoRestaurante1;
    private JITelaPedidoRestaurante2 viewPedidoRestaurante2;
    //Precisa de uma tela de usuário?
    private TelaUsuarioController controller;
    
    /**
     * Creates new form JITelaPagamento
     */
    public JITelaPagamento() {
        initComponents();
        this.viewPedidoRestaurante1 = viewPedidoRestaurante1;
        this.viewPedidoRestaurante2 = viewPedidoRestaurante2;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbFinalizarPagamento = new javax.swing.JButton();
        jbPix = new javax.swing.JButton();
        jbEntrega = new javax.swing.JButton();
        jbCCredito = new javax.swing.JButton();
        jbCDebito = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jlTipoPagamento = new javax.swing.JLabel();
        jComboBoxPdts = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlQtdProdutos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlPrecoTotal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        setTitle("Definição do pagamento");

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlSair.setBackground(new java.awt.Color(102, 51, 0));
        jlSair.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jlSair.setForeground(new java.awt.Color(102, 51, 0));
        jlSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSair.setText("X");
        jlSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSair, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSair))
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione a forma de pagamento desejada");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbFinalizarPagamento.setBackground(new java.awt.Color(255, 255, 255));
        jbFinalizarPagamento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbFinalizarPagamento.setForeground(new java.awt.Color(102, 51, 0));
        jbFinalizarPagamento.setText("Efetuar pagamento");
        jbFinalizarPagamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 4));
        jbFinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarPagamentoActionPerformed(evt);
            }
        });

        jbPix.setBackground(new java.awt.Color(255, 255, 255));
        jbPix.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbPix.setForeground(new java.awt.Color(102, 51, 0));
        jbPix.setText("Pix");
        jbPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPixActionPerformed(evt);
            }
        });

        jbEntrega.setBackground(new java.awt.Color(255, 255, 255));
        jbEntrega.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbEntrega.setForeground(new java.awt.Color(102, 51, 0));
        jbEntrega.setText("Durante a entrega");
        jbEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntregaActionPerformed(evt);
            }
        });

        jbCCredito.setBackground(new java.awt.Color(255, 255, 255));
        jbCCredito.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbCCredito.setForeground(new java.awt.Color(102, 51, 0));
        jbCCredito.setText("Cartão de crédito");
        jbCCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCCreditoActionPerformed(evt);
            }
        });

        jbCDebito.setBackground(new java.awt.Color(255, 255, 255));
        jbCDebito.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbCDebito.setForeground(new java.awt.Color(102, 51, 0));
        jbCDebito.setText("Cartão de débito");
        jbCDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCDebitoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Forma de pagamento selecionada:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlTipoPagamento.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlTipoPagamento.setForeground(new java.awt.Color(255, 255, 255));
        jlTipoPagamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTipoPagamento.setText("Não selecionada.");
        jlTipoPagamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jlTipoPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBoxPdts.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPdts.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBoxPdts.setForeground(new java.awt.Color(102, 51, 0));
        jComboBoxPdts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 4));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantidade total de produtos:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Descontos aplicados:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Preço total:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlQtdProdutos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlQtdProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jlQtdProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlQtdProdutos.setText("0");
        jlQtdProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jlQtdProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nenhum.");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlPrecoTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlPrecoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlPrecoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrecoTotal.setText("0");
        jlPrecoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jlPrecoTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jlTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jlQtdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jbPix, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPdts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jbFinalizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(385, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jbCCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbCDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQtdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jComboBoxPdts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFinalizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSairMouseClicked
        // TODO add your handling code here:
        controller.sairDuranteTelaPagamento();
    }//GEN-LAST:event_jlSairMouseClicked

    private void jbPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPixActionPerformed
        // TODO add your handling code here:
        controller.efetuarPagamentoPix();
    }//GEN-LAST:event_jbPixActionPerformed

    private void jbEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntregaActionPerformed
        // TODO add your handling code here:
        controller.efetuarPagamentoEntrega();
    }//GEN-LAST:event_jbEntregaActionPerformed

    private void jbCCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCCreditoActionPerformed
        // TODO add your handling code here:
        controller.efetuarPagamentoCCredito();
    }//GEN-LAST:event_jbCCreditoActionPerformed

    private void jbCDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCDebitoActionPerformed
        // TODO add your handling code here:
        controller.efetuarPagamentoCDebito();
    }//GEN-LAST:event_jbCDebitoActionPerformed

    private void jbFinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarPagamentoActionPerformed
        // TODO add your handling code here:
        //Atualizará a tabela de pedidos:
        controller.preencherListaPedidos();
        controller.efetuarPagamentoFinal();
    }//GEN-LAST:event_jbFinalizarPagamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPdts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCCredito;
    private javax.swing.JButton jbCDebito;
    private javax.swing.JButton jbEntrega;
    private javax.swing.JButton jbFinalizarPagamento;
    private javax.swing.JButton jbPix;
    private javax.swing.JLabel jlPrecoTotal;
    private javax.swing.JLabel jlQtdProdutos;
    private javax.swing.JLabel jlSair;
    private javax.swing.JLabel jlTipoPagamento;
    // End of variables declaration//GEN-END:variables

    
    
    //Getters e setters usados:
    
    public JComboBox<String> getjComboBoxPdts() {
        return jComboBoxPdts;
    }

    public void setjComboBoxPdts(JComboBox<String> jComboBoxPdts) {
        this.jComboBoxPdts = jComboBoxPdts;
    }

    public JButton getJbCCredito() {
        return jbCCredito;
    }

    public void setJbCCredito(JButton jbCCredito) {
        this.jbCCredito = jbCCredito;
    }

    public JButton getJbCDebito() {
        return jbCDebito;
    }

    public void setJbCDebito(JButton jbCDebito) {
        this.jbCDebito = jbCDebito;
    }

    public JButton getJbEntrega() {
        return jbEntrega;
    }

    public void setJbEntrega(JButton jbEntrega) {
        this.jbEntrega = jbEntrega;
    }

    public JButton getJbFinalizarPagamento() {
        return jbFinalizarPagamento;
    }

    public void setJbFinalizarPagamento(JButton jbFinalizarPagamento) {
        this.jbFinalizarPagamento = jbFinalizarPagamento;
    }

    public JButton getJbPix() {
        return jbPix;
    }

    public void setJbPix(JButton jbPix) {
        this.jbPix = jbPix;
    }

    public JLabel getJlPrecoTotal() {
        return jlPrecoTotal;
    }

    public void setJlPrecoTotal(JLabel jlPrecoTotal) {
        this.jlPrecoTotal = jlPrecoTotal;
    }

    public JLabel getJlQtdProdutos() {
        return jlQtdProdutos;
    }

    public void setJlQtdProdutos(JLabel jlQtdProdutos) {
        this.jlQtdProdutos = jlQtdProdutos;
    }

    public JLabel getJlTipoPagamento() {
        return jlTipoPagamento;
    }

    public void setJlTipoPagamento(JLabel jlTipoPagamento) {
        this.jlTipoPagamento = jlTipoPagamento;
    }



    
    
    
    


}
