/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package unifacs.view;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import unifacs.controller.TelaUsuarioController;

/**
 *
 * @author YellowRed
 */
public class JITelaPedidoRestaurante2 extends javax.swing.JInternalFrame {
    
    private JITelaPagamento viewTelaPagamento;
    private JIFazerPedido viewFazerPedido;
    private TelaUsuarioController controller;

    /**
     * Creates new form JITelaPedidoRestaurante1
     */
    public JITelaPedidoRestaurante2() {
        initComponents();
        this.viewFazerPedido = viewFazerPedido;
        this.viewTelaPagamento  = viewTelaPagamento;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaAlmoco = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbIrPPagamentoR2 = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbApagarTudo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelaPizzas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabelaBebidas = new javax.swing.JTable();
        jComboBoxPdts = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jlPrecoTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlQtdProdutos = new javax.swing.JLabel();

        setTitle("Pedido - Restaurante Sabor Estrangeiro");
        setPreferredSize(new java.awt.Dimension(1650, 560));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlSair.setBackground(new java.awt.Color(102, 51, 0));
        jlSair.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jlSair.setForeground(new java.awt.Color(102, 51, 0));
        jlSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSair.setText("X");
        jlSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSair, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSair))
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sabor Estrangeiro");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTabelaAlmoco.setBackground(new java.awt.Color(255, 255, 255));
        jTabelaAlmoco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        jTabelaAlmoco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabelaAlmoco.setForeground(new java.awt.Color(204, 102, 0));
        jTabelaAlmoco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtd estocada", "Nome", "Tamanho", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaAlmoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaAlmocoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaAlmoco);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produtos selecionados");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descontos adicionados:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("descontos indisponíveis.");

        jbIrPPagamentoR2.setBackground(new java.awt.Color(255, 255, 255));
        jbIrPPagamentoR2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbIrPPagamentoR2.setForeground(new java.awt.Color(102, 51, 0));
        jbIrPPagamentoR2.setText("Continuar");
        jbIrPPagamentoR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIrPPagamentoR2ActionPerformed(evt);
            }
        });

        jbRemover.setBackground(new java.awt.Color(255, 255, 255));
        jbRemover.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jbRemover.setForeground(new java.awt.Color(102, 51, 0));
        jbRemover.setText("Remover");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jbApagarTudo.setBackground(new java.awt.Color(255, 0, 0));
        jbApagarTudo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jbApagarTudo.setForeground(new java.awt.Color(255, 255, 255));
        jbApagarTudo.setText("Apagar tudo");
        jbApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarTudoActionPerformed(evt);
            }
        });

        jTabelaPizzas.setBackground(new java.awt.Color(255, 255, 255));
        jTabelaPizzas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        jTabelaPizzas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabelaPizzas.setForeground(new java.awt.Color(204, 102, 0));
        jTabelaPizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtd estocada", "Nome", "Tamanho", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaPizzasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTabelaPizzas);

        jTabelaBebidas.setBackground(new java.awt.Color(255, 255, 255));
        jTabelaBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        jTabelaBebidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabelaBebidas.setForeground(new java.awt.Color(204, 102, 0));
        jTabelaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtd estocada", "Nome", "Tamanho", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaBebidasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTabelaBebidas);

        jComboBoxPdts.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPdts.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBoxPdts.setForeground(new java.awt.Color(102, 51, 0));
        jComboBoxPdts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 4));
        jComboBoxPdts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxPdtsMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preço total:");

        jlPrecoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlPrecoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlPrecoTotal.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qtd de produtos:");

        jlQtdProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQtdProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jlQtdProdutos.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 459, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbIrPPagamentoR2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jlPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jlQtdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addComponent(jComboBoxPdts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbApagarTudo))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jlPrecoTotal)
                            .addComponent(jlQtdProdutos))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPdts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbRemover)
                            .addComponent(jbApagarTudo))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addComponent(jbIrPPagamentoR2)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSairMouseClicked
        // TODO add your handling code here:
        controller.sairDurantePedidoR2();
        
    }//GEN-LAST:event_jlSairMouseClicked

    private void jbIrPPagamentoR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIrPPagamentoR2ActionPerformed
        // TODO add your handling code here:
        controller.abrirTelaPagamentoR2();
    }//GEN-LAST:event_jbIrPPagamentoR2ActionPerformed

    private void jbApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarTudoActionPerformed
        // TODO add your handling code here:
        controller.removerTudoR2();
    }//GEN-LAST:event_jbApagarTudoActionPerformed

    private void jTabelaAlmocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaAlmocoMouseClicked
        // Tabela almoço - Seleção!
        controller.produtoSelecionadoTAlmoco();
    }//GEN-LAST:event_jTabelaAlmocoMouseClicked

    private void jTabelaBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaBebidasMouseClicked
        // TODO add your handling code here:
        controller.produtoSelecionadoTBebidasR2();
    }//GEN-LAST:event_jTabelaBebidasMouseClicked

    private void jTabelaPizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPizzasMouseClicked
        // TODO add your handling code here:
        controller.produtoSelecionadoTPizzas();
    }//GEN-LAST:event_jTabelaPizzasMouseClicked

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        // TODO add your handling code here:
        controller.removerPdtsSelecionadosR2();
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jComboBoxPdtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPdtsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPdtsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPdts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabelaAlmoco;
    private javax.swing.JTable jTabelaBebidas;
    private javax.swing.JTable jTabelaPizzas;
    private javax.swing.JButton jbApagarTudo;
    private javax.swing.JButton jbIrPPagamentoR2;
    private javax.swing.JButton jbRemover;
    private javax.swing.JLabel jlPrecoTotal;
    private javax.swing.JLabel jlQtdProdutos;
    private javax.swing.JLabel jlSair;
    // End of variables declaration//GEN-END:variables

    
    
    
    
        //Getters e setters:
    
    
    public JTable getjTabelaAlmoco() {
        return jTabelaAlmoco;
    }

    public void setjTabelaAlmoco(JTable jTabelaAlmoco) {
        this.jTabelaAlmoco = jTabelaAlmoco;
    }

    public JTable getjTabelaBebidas() {
        return jTabelaBebidas;
    }

    public void setjTabelaBebidas(JTable jTabelaBebidas) {
        this.jTabelaBebidas = jTabelaBebidas;
    }

    public JTable getjTabelaPizzas() {
        return jTabelaPizzas;
    }

    public void setjTabelaPizzas(JTable jTabelaPizzas) {
        this.jTabelaPizzas = jTabelaPizzas;
    }

    public JLabel getJlPrecoTotal() {
        return jlPrecoTotal;
    }

    public void setJlPrecoTotal(JLabel jlPrecoTotal) {
        this.jlPrecoTotal = jlPrecoTotal;
    }

    public JLabel getJlQtdProdutos() {
        return jlQtdProdutos;
    }

    public void setJlQtdProdutos(JLabel jlQtdProdutos) {
        this.jlQtdProdutos = jlQtdProdutos;
    }

   
   

    public JComboBox<String> getjComboBoxPdts() {
        return jComboBoxPdts;
    }

    public void setjComboBoxPdts(JComboBox<String> jComboBoxPdts) {
        this.jComboBoxPdts = jComboBoxPdts;
    }










    
    
















}
