/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unifacs.view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import unifacs.controller.TelaUsuarioController;
import unifacs.model.Cliente;

/**
 *
 * @author YellowRed
 */
public class TelaUsuario extends javax.swing.JFrame {

    //Cliente:
    private Cliente clienteUsuario = new Cliente();
    //Telas internas da aplicação.    
    private JIFazerPedido viewFazerPedido;
    private JITelaPedidoRestaurante1 viewPedidoRestaurante1;
    private JITelaPedidoRestaurante2 viewPedidoRestaurante2;
    private JITelaPagamento viewTelaPagamento;
    private JITelaVisualizarConta viewVisualizarConta;

    //Controller:
    private TelaUsuarioController controller;
    // Ganhar uma variável que dirá que o restaurante 1 deve abrir a tela Fazer pedido deve ser fechada.

    /**
     * Creates new form TelaUsuario
     *
     */
    //Construtor para testes:
    public TelaUsuario() {

    }

    public TelaUsuario(Cliente clienteUsuario) {
        initComponents();
        this.clienteUsuario = clienteUsuario;
        this.viewFazerPedido = new JIFazerPedido();
        this.viewPedidoRestaurante1 = new JITelaPedidoRestaurante1();
        this.viewPedidoRestaurante2 = new JITelaPedidoRestaurante2();
        this.viewTelaPagamento = new JITelaPagamento();
        this.viewVisualizarConta = new JITelaVisualizarConta();

        this.controller = new TelaUsuarioController(clienteUsuario, this, viewVisualizarConta, viewPedidoRestaurante1, viewPedidoRestaurante2, viewTelaPagamento, viewFazerPedido);

        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlSaudacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabelaPedidos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbFazerUmPedido = new javax.swing.JButton();
        jAreaDeTrabalho = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jmBarraMenu = new javax.swing.JMenuBar();
        jmVisualizarConta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmDesconectarConta = new javax.swing.JMenuItem();
        jmExcluirConta = new javax.swing.JMenuItem();
        jmSairFastLunch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha área");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jlSaudacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlSaudacao.setForeground(new java.awt.Color(255, 255, 255));
        jlSaudacao.setText("Olá, faça um pedido! ");
        jlSaudacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSaudacaoMouseClicked(evt);
            }
        });

        jtTabelaPedidos.setBackground(new java.awt.Color(153, 102, 0));
        jtTabelaPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "- Lista de pedidos -", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 51, 0))); // NOI18N
        jtTabelaPedidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtTabelaPedidos.setForeground(new java.awt.Color(102, 51, 0));
        jtTabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabelaPedidos);

        jLabel3.setBackground(new java.awt.Color(51, 0, 0));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descontos disponíveis!");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avisos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 204, 51))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbFazerUmPedido.setBackground(new java.awt.Color(255, 255, 255));
        jbFazerUmPedido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jbFazerUmPedido.setForeground(new java.awt.Color(102, 51, 0));
        jbFazerUmPedido.setText("Fazer um pedido");
        jbFazerUmPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 4));
        jbFazerUmPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFazerUmPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbFazerUmPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlSaudacao)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jbFazerUmPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\estudos\\gitGithubInstalacoes\\projetosPessoais\\Projeto-Aplicacao-Java\\a3javaaplicacao\\src\\test\\java\\unifacs\\view\\images\\background\\backgroundOficialUsuario.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jAreaDeTrabalho.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jAreaDeTrabalho);
        jAreaDeTrabalho.setLayout(jAreaDeTrabalhoLayout);
        jAreaDeTrabalhoLayout.setHorizontalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, Short.MAX_VALUE)
        );
        jAreaDeTrabalhoLayout.setVerticalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jAreaDeTrabalho))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jAreaDeTrabalho)
        );

        jmBarraMenu.setBackground(new java.awt.Color(102, 51, 0));
        jmBarraMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 5));
        jmBarraMenu.setForeground(new java.awt.Color(0, 0, 0));

        jmVisualizarConta.setBackground(new java.awt.Color(0, 0, 0));
        jmVisualizarConta.setBorder(null);
        jmVisualizarConta.setForeground(new java.awt.Color(0, 0, 0));
        jmVisualizarConta.setText(" Opções");
        jmVisualizarConta.setActionCommand("Minha conta");
        jmVisualizarConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmVisualizarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmVisualizarConta.setPreferredSize(new java.awt.Dimension(100, 50));

        jMenuItem1.setText("Vizualizar conta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmVisualizarConta.add(jMenuItem1);

        jmDesconectarConta.setText("Desconectar conta");
        jmDesconectarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDesconectarContaActionPerformed(evt);
            }
        });
        jmVisualizarConta.add(jmDesconectarConta);

        jmExcluirConta.setText("Excluir conta");
        jmExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExcluirContaActionPerformed(evt);
            }
        });
        jmVisualizarConta.add(jmExcluirConta);

        jmSairFastLunch.setText("Sair");
        jmSairFastLunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairFastLunchActionPerformed(evt);
            }
        });
        jmVisualizarConta.add(jmSairFastLunch);

        jmBarraMenu.add(jmVisualizarConta);

        setJMenuBar(jmBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //Aqui 

        controller.abrirTelaVisualizarConta();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbFazerUmPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFazerUmPedidoActionPerformed
        // TODO add your handling code here:

        controller.abrirTelaFazerPedido();
        //Crie uma condição que faça com que os outras  JI apareçam.

    }//GEN-LAST:event_jbFazerUmPedidoActionPerformed

    private void jmSairFastLunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairFastLunchActionPerformed
        // TODO add your handling code here:
        //Sair do aplicativo.
        controller.sairDoFastLunch();
    }//GEN-LAST:event_jmSairFastLunchActionPerformed

    private void jmExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExcluirContaActionPerformed
        //Excluir conta:
        controller.excluirContaUsuario();

    }//GEN-LAST:event_jmExcluirContaActionPerformed

    private void jmDesconectarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDesconectarContaActionPerformed
        // Desconectar conta: apenas sair da tela usuário, porém o cliente cadastrado ainda existe.
        controller.desconectarContaUsuario();
    }//GEN-LAST:event_jmDesconectarContaActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        //AQUI
        controller.darSaudacaoUsuario();

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jlSaudacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSaudacaoMouseClicked
        // TODO add your handling code here:
        controller.darSaudacaoUsuario();

    }//GEN-LAST:event_jlSaudacaoMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        controller.darSaudacaoUsuario();

    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaDeTrabalho;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbFazerUmPedido;
    private javax.swing.JLabel jlSaudacao;
    private javax.swing.JMenuBar jmBarraMenu;
    private javax.swing.JMenuItem jmDesconectarConta;
    private javax.swing.JMenuItem jmExcluirConta;
    private javax.swing.JMenuItem jmSairFastLunch;
    private javax.swing.JMenu jmVisualizarConta;
    private javax.swing.JTable jtTabelaPedidos;
    // End of variables declaration//GEN-END:variables

    //Getters e setters usados:
    public JDesktopPane getjAreaDeTrabalho() {
        return jAreaDeTrabalho;
    }

    public void setjAreaDeTrabalho(JDesktopPane jAreaDeTrabalho) {
        this.jAreaDeTrabalho = jAreaDeTrabalho;
    }

    public JLabel getJlSaudacao() {
        return jlSaudacao;
    }

    public void setJlSaudacao(JLabel jlSaudacao) {
        this.jlSaudacao = jlSaudacao;
    }

    public Cliente getClienteUsuario() {
        return clienteUsuario;
    }

    public void setClienteUsuario(Cliente clienteUsuario) {
        this.clienteUsuario = clienteUsuario;
    }

}
